title: Cristian Urlea
email: 
description: > #
  A functional corner of the world. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cristian.urlea.ro" # the base hostname & protocol for your site
twitter_username: 
github_username:  cristianurlea

markdown: kramdown
